repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v5.0.0
    hooks:
    - id: check-merge-conflict
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    - id: yesqa
  - repo: local
    hooks:
      - id: formatting_project
        name: Formatting
        entry: make format
        language: python
        pass_filenames: false
        always_run: true
      - id: linting_project
        name: Linting
        entry: make lint
        language: python
        pass_filenames: false
        always_run: true
      - id: tests_project
        name: Tests
        entry: make test
        language: python
        pass_filenames: false
        always_run: true
        stages: [pre-push]
