[mypy]
python_version = 3.12
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
check_untyped_defs = True

[mypy-grpc.*]
ignore_missing_imports = True

[mypy-grpc_health.*]
ignore_missing_imports = True

[mypy-grpc_reflection.*]
ignore_missing_imports = True

[mypy-google.protobuf.*]
ignore_missing_imports = True

[mypy-grpc_tools.*]
ignore_missing_imports = True

[mypy-watchfiles.*]
ignore_missing_imports = True
